services:
  clickhouse:
    image: clickhouse/clickhouse-server:26.2
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: test
      CLICKHOUSE_DB: default
